Script_TD_CN
% Makes the interface behave as a subsonic compact nozzle (simulates the
% acoustic response of a subsonic compact nozzle to impinging acoustic and
% entropic perturbations, based on the theory of Marble & Candel (1977))
% Created 2015-11-03 by Erwan Rollan(eor21@cam.ac.uk)
global CI


%% Calculate nozzle response (Executed for each time step at the correct interface)



switch CI.TD.CN.type 
    case 1 % Only acoustic-acoustic transfer functions are enabled
        % Backward Wave in the Upstream section
        x(2,:)... % AM(ss)
            =Fcn_lsim_varied_td(   CI.TD.AP(ss,:),...
            CI.TD.CN.GreensysEntropyP1m,...
            CI.TD.Green.tauConv2(2),...
            Var,...
            CI.TP.tau_plus(ss) + CI.BC.CN.tau_dP1m,...
            CI.TD.dt)...
            +Fcn_lsim_varied_td(   CI.TD.AM(ss+1,:),...
            CI.TD.CN.GreensysEntropyP1mu,...
            CI.TD.Green.tauConv2(2),...
            Var,...
            CI.TP.tau_minus(ss+1) + CI.BC.CN.tau_dP1mu,...
            CI.TD.dt);
        
        
        % Forward Wave in the Dowstream section
        x(1,:)... % AP(ss+1)
            = Fcn_lsim_varied_td(   CI.TD.AP(ss,:),...
            CI.TD.CN.GreensysEntropyP2p,...
            CI.TD.Green.tauConv2(2),...
            Var,...
            CI.TP.tau_plus(ss) + CI.BC.CN.tau_dP2p,...
            CI.TD.dt)...
            +Fcn_lsim_varied_td(   CI.TD.AM(ss+1,:),...
            CI.TD.CN.GreensysEntropyP2pu,...
            CI.TD.Green.tauConv2(2),...
            Var,...
            CI.TP.tau_minus(ss+1) + CI.BC.CN.tau_dP2pu,...
            CI.TD.dt);
        
        
    case 2 % Only entropic-acoustic transfer functions are enabled
        % Backward Wave in the Upstream section
        x(2,:)... % AM(ss)
            = Fcn_lsim_varied_td(   CI.TD.E(ss,:),...
            CI.TD.CN.GreensysEntropy1m,... % Change this once a green's function has been made
            0,...
            Var,...
            CI.TP.tau_c(ss) + CI.BC.CN.tau_d1m,...
            CI.TD.dt)   ;
        
        % Forward Wave in the Downstream section
        x(1,:)... % AP(ss+1)
            = Fcn_lsim_varied_td(   CI.TD.E(ss,:),...
            CI.TD.CN.GreensysEntropy2p,... % Change this once a green's function has been made
            0,...
            Var,...
            CI.TP.tau_c(ss) + CI.BC.CN.tau_d2p,...
            CI.TD.dt)   ;
        
        
    case 3 % Both acoustic-acoustic and entropic-acoustic transfer functions are enabled
        % Backward Wave in the Upstream section
        x(2,:)... % AM(ss)
            =Fcn_lsim_varied_td(   CI.TD.AP(ss,:),...
            CI.TD.CN.GreensysEntropyP1m,...
            CI.TD.Green.tauConv2(2),...
            Var,...
            CI.TP.tau_plus(ss) + CI.BC.CN.tau_dP1m,...
            CI.TD.dt)...
            +Fcn_lsim_varied_td(   CI.TD.AM(ss+1,:),...
            CI.TD.CN.GreensysEntropyP1mu,...
            CI.TD.Green.tauConv2(2),...
            Var,...
            CI.TP.tau_minus(ss+1) + CI.BC.CN.tau_dP1mu,...
            CI.TD.dt)...
            + Fcn_lsim_varied_td(   CI.TD.E(ss,:),...
            CI.TD.CN.GreensysEntropy1m,... % Change this once a green's function has been made
            CI.TD.Green.tauConv2(2),...
            Var,...
            CI.TP.tau_c(ss) + CI.BC.CN.tau_d1m,...
            CI.TD.dt)   ;
        
        
        % Forward Wave in the Downstream section
        x(1,:)... % AP(ss+1)
            = Fcn_lsim_varied_td(   CI.TD.AP(ss,:),...
            CI.TD.CN.GreensysEntropyP2p,...
            CI.TD.Green.tauConv2(2),...
            Var,...
            CI.TP.tau_plus(ss) + CI.BC.CN.tau_dP2p,...
            CI.TD.dt)...
            +Fcn_lsim_varied_td(   CI.TD.AM(ss+1,:),...
            CI.TD.CN.GreensysEntropyP2pu,...
            CI.TD.Green.tauConv2(2),...
            Var,...
            CI.TP.tau_minus(ss+1) + CI.BC.CN.tau_dP2pu,...
            CI.TD.dt)...
            + Fcn_lsim_varied_td(   CI.TD.E(ss,:),...
            CI.TD.CN.GreensysEntropy2p,...
            CI.TD.Green.tauConv2(2),...
            Var,...
            CI.TP.tau_c(ss) + CI.BC.CN.tau_d2p,...
            CI.TD.dt)   ;
end

x(3,:)=y(3); % The Entropy wave is propagated
end
